 READ HEAD & TAIL OF DATA FILE

In [1]:
import pandas as pd

FILE

In [2]:

#  file ka head dekhne ke liye use hota hai
# df.head()

csv_file = pd.read_csv("G:\downloads\student_marks.csv")

df.head()

In [5]:
#file head dekhne ke liye use hota hai
#csv_file.head() ise upar ke 5 rows ka head dekhne ke liye use hota hai
#csv_file.head(7) # 7 rows ka head dekhne ke liye use hota hai
csv_file.head()
csv_file.head(7)

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
0,John,M,05-04-1988,55,45,56,87,21,52,89,65
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52
6,pooja,F,04-05-1987,55,64,61,58,75,58,64,61

df.tail()

In [6]:
#file tail dekhne ke liye use hota hai
#csv_file.tail() ise neeche ke 5 rows ka tail dekhne ke liye use hota hai
#csv_file.tail(7) # 7 rows ka tail dekhne ke liye use hota hai
csv_file.tail()
csv_file.tail(7)

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52
6,pooja,F,04-05-1987,55,64,61,58,75,58,64,61
7,Ritesh,M,25-05-1989,54,76,87,56,25,56,76,87
8,Farha,F,12-08-1990,55,63,89,75,78,75,63,89
9,Mukesh,M,02-09-1989,96,46,77,83,58,83,46,77